### ISSUE TITLE
마이페이지 기능 구현

### ISSUE THREAD

**Issue by jaem0629** [chocojaem/danvery#6]
- [x]  내가 쓴 글, 내가 쓴 댓글, 좋아요한 글을 가져와서 표기해주는 기능을 구현
- [x]  프로필 수정 구현
- [x]  디스플레이 설정으로는 다크모드와 언어 선택을 구현

**Comment by jaem0629** [comment]
다크모드는 디자인이 나오는대로 사용자의 다크모드 선택 여부에 따라 기존 라이트 모드의 Palette의 색상을 치환 시키는 형식으로 진행

**Comment by developerChans** [comment]
댓글로 단것 우선적으로 하기

- [x] 닉네임 변경
