### ISSUE TITLE
게시판 페이지 기능 구현

### ISSUE THREAD

**Issue by jaem0629** [chocojaem/danvery#7]
- [x]  게시글 작성시 사진 업로드 가능하도록
- [x]  게시판 로드시 사진도 로드 될 수 있도록
- [x] 청원 게시글 청원상태 영어 -> 한국어 변경
- [x] 청원게시판이 기존 view -> 원형 그래프가 포함된 view로 변경
- [x] 게시글 검색시 청원 게시판도 적용
- [x] 청원 게시판 동의시 바로 카운트 적용될 수 있도록
- [x] 청원 게시글 작성 구현
- [x] 청원 게시글 기간 만료시 동의 못하게
- [x] 청원 이미 동의 한 글에는 동의 버튼 막히게(백엔드 작업 이후)
- [x] 게시글 시간을 분단위, 시간단위, 일단위로 나눠 표기
- [ ] 청원, 자유 게시판 댓글 좋아요 <- 이건 좀 더 고민(현재 디자인으론 안됨)
- [x] 청원 게시판에 파일이 올라올 경우 이미지와 나눠처리
- [x] 청원 게시글 조회시 스크롤 안될 경우 RefreshIndicator 안나타나는 거 해결
- [x] html 태그 문제로 \n으로 오는 body를 <br>로 replace 할 것
- [x] 청원 게시글 블라인드 기능 추가

**Comment by developerChans** [comment]
댓글로 단것 우선적으로 하기

- [x] [FEATURE] 게시글 신고기능 삽입

청원게시판 자유게시판 QnA 게시판

신고 목록

욕설/비하
낚시/놀람/도배
광고성 게시글
정당, 정치인 비하 및 선거운동
음란물/불건전한 만남 및 대화
게시판 성격에 부적합
유출/사칭/사기
